### ISSUE TITLE
Crash when no audio interface is available

### ISSUE THREAD

**Issue by joshleong** [keijiro/KlakLasp#2] opened 2017-07-23 16:28 UTC
Hi Keijiro, I've attempted to run some of the samples and build something from scratch using the Klak and Lasp Libraries and Unity is Crashing on me consistently.

Machine:
Model: MacPro6,1, BootROM MP61.0116.B17, 6 processors, 6-Core Intel Xeon E5, 3.5 GHz, 64 GB, SMC 2.20f18
Graphics: AMD FirePro D500, AMD FirePro D500, PCIe, 3072 MB

[errlog.txt](https://github.com/keijiro/KlakLasp/files/1168608/errlog.txt)

**Comment by keijiro** [comment] 2017-07-24 01:44
(The original commend was editor for ease of read)

**Comment by keijiro** [comment] 2017-07-24 01:51
Could you give me some information about the audio input device you're using:

- Product name
- USB or Thunderbolt?

**Comment by joshleong** [comment] 2017-07-25 00:35
I'm using an OP-1, and it's going through USB.

**Comment by joshleong** [comment] 2017-07-25 00:37
Although I thought you could also use it with an Audio Source within Unity.

**Comment by keijiro** [comment] 2017-07-25 01:39
If I remember correctly, OP-1 doesn't work as audio input/output interface. Could you confirm it?

At the moment KlakLASP doesn't support input from Audio Source.

**Comment by joshleong** [comment] 2017-07-27 18:47
Alright I'll try to verify, what's the simplest setup to get klak-lasp working?

**Comment by keijiro** [comment] 2017-07-28 12:31
Use a proper audio interface. Then it might work.

**Comment by keijiro** [comment] 2017-07-30 01:09
Title changed. The plugin shouldn't crash even when there is no available audio interface on the system. It should output a proper error message and continue running with null input. This issue might be easily reproducible with Mac Pro (because it doesn't have a built-in audio interface).

**Comment by joshleong** [comment] 2017-08-05 04:54
I'll have an audio interface I can test with tomorrow.

**Comment by joshleong** [comment] 2017-08-06 22:27
I bought a Focusrite Scarlett Solo for an audio interface, Unity doesn't crash on compile anymore, although I see that LASP is pulling from the first channel, which is the mic channel on the Focusrite, I currently have the OP-1 connected to the second channel which has a normal 1/4". Might try a 3.5MM to XLR connection.

Thanks for the great unity plugin!

**Comment by keijiro** [comment] 2017-08-15 02:19
This issue was moved to the LASP project. https://github.com/keijiro/Lasp/issues/5

I'm closing this ticket now. Thanks for pointing out the issue.

**Closed as completed by keijiro** 2017-08-15 02:19 UTC
Labels: bug
